export enum TEXT {
  RATING = 'rating:',
  SHOW = 'show',
  SEARCH = 'Search',
  ORDER = 'Order online',
  COLLECT = 'collect in store',
  FIND_GADGET = 'Find your Gadget',
  GET_STARTED = 'Get started',
  LOGIN = 'Login',
  WELCOME = 'Welcome back',
  FORGOT = 'Forgot passcode?',
  ACCOUNT = 'Create account',
  INVALID_EMAIL = 'Invalid email format',
  EMAIL_REQUIRED = 'Email is required',
  MIN_PASSWORD = 'Password must be at least 8 characters',
  MAX_PASSWORD = 'Password must be at most 20 characters',
  PASSWORD_REQUIRED = 'Password is required',
  EMAIL = 'Email',
  PASSWORD = 'Password',
  GETSTARTED = 'getstarted',
  PRODUCT = 'product',
  password = 'password',
  email = 'email',
}
